/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarenkorbRouteImport } from './routes/warenkorb'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KasseRouteImport } from './routes/kasse'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as FuellungenRouteImport } from './routes/fuellungen'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ColorsRouteImport } from './routes/colors'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TortenIndexRouteImport } from './routes/torten/index'
import { Route as TortenSlugRouteImport } from './routes/torten/$slug'
import { Route as BestellungOrderNoRouteImport } from './routes/bestellung/$orderNo'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthAppRouteRouteImport } from './routes/_auth/app/route'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthAppFuellungenRouteImport } from './routes/_auth/app/fuellungen'
import { Route as AuthAppProdukteIndexRouteImport } from './routes/_auth/app/produkte/index'
import { Route as AuthAppProdukteNeuRouteImport } from './routes/_auth/app/produkte/neu'
import { Route as AuthAppProdukteIdRouteImport } from './routes/_auth/app/produkte/$id'
import { Route as AuthAppBestellungenIdRouteImport } from './routes/_auth/app/bestellungen.$id'

const WarenkorbRoute = WarenkorbRouteImport.update({
  id: '/warenkorb',
  path: '/warenkorb',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KasseRoute = KasseRouteImport.update({
  id: '/kasse',
  path: '/kasse',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const FuellungenRoute = FuellungenRouteImport.update({
  id: '/fuellungen',
  path: '/fuellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorsRoute = ColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TortenIndexRoute = TortenIndexRouteImport.update({
  id: '/torten/',
  path: '/torten/',
  getParentRoute: () => rootRouteImport,
} as any)
const TortenSlugRoute = TortenSlugRouteImport.update({
  id: '/torten/$slug',
  path: '/torten/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BestellungOrderNoRoute = BestellungOrderNoRouteImport.update({
  id: '/bestellung/$orderNo',
  path: '/bestellung/$orderNo',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppFuellungenRoute = AuthAppFuellungenRouteImport.update({
  id: '/fuellungen',
  path: '/fuellungen',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppProdukteIndexRoute = AuthAppProdukteIndexRouteImport.update({
  id: '/produkte/',
  path: '/produkte/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppProdukteNeuRoute = AuthAppProdukteNeuRouteImport.update({
  id: '/produkte/neu',
  path: '/produkte/neu',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppProdukteIdRoute = AuthAppProdukteIdRouteImport.update({
  id: '/produkte/$id',
  path: '/produkte/$id',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppBestellungenIdRoute = AuthAppBestellungenIdRouteImport.update({
  id: '/bestellungen/$id',
  path: '/bestellungen/$id',
  getParentRoute: () => AuthAppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/colors': typeof ColorsRoute
  '/datenschutz': typeof DatenschutzRoute
  '/fuellungen': typeof FuellungenRoute
  '/galerie': typeof GalerieRoute
  '/impressum': typeof ImpressumRoute
  '/kasse': typeof KasseRoute
  '/kontakt': typeof KontaktRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/warenkorb': typeof WarenkorbRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/bestellung/$orderNo': typeof BestellungOrderNoRoute
  '/torten/$slug': typeof TortenSlugRoute
  '/torten/': typeof TortenIndexRoute
  '/app/fuellungen': typeof AuthAppFuellungenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/': typeof AuthAppIndexRoute
  '/app/bestellungen/$id': typeof AuthAppBestellungenIdRoute
  '/app/produkte/$id': typeof AuthAppProdukteIdRoute
  '/app/produkte/neu': typeof AuthAppProdukteNeuRoute
  '/app/produkte/': typeof AuthAppProdukteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/colors': typeof ColorsRoute
  '/datenschutz': typeof DatenschutzRoute
  '/fuellungen': typeof FuellungenRoute
  '/galerie': typeof GalerieRoute
  '/impressum': typeof ImpressumRoute
  '/kasse': typeof KasseRoute
  '/kontakt': typeof KontaktRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/warenkorb': typeof WarenkorbRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/bestellung/$orderNo': typeof BestellungOrderNoRoute
  '/torten/$slug': typeof TortenSlugRoute
  '/torten': typeof TortenIndexRoute
  '/app/fuellungen': typeof AuthAppFuellungenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthAppIndexRoute
  '/app/bestellungen/$id': typeof AuthAppBestellungenIdRoute
  '/app/produkte/$id': typeof AuthAppProdukteIdRoute
  '/app/produkte/neu': typeof AuthAppProdukteNeuRoute
  '/app/produkte': typeof AuthAppProdukteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/agb': typeof AgbRoute
  '/colors': typeof ColorsRoute
  '/datenschutz': typeof DatenschutzRoute
  '/fuellungen': typeof FuellungenRoute
  '/galerie': typeof GalerieRoute
  '/impressum': typeof ImpressumRoute
  '/kasse': typeof KasseRoute
  '/kontakt': typeof KontaktRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/warenkorb': typeof WarenkorbRoute
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/bestellung/$orderNo': typeof BestellungOrderNoRoute
  '/torten/$slug': typeof TortenSlugRoute
  '/torten/': typeof TortenIndexRoute
  '/_auth/app/fuellungen': typeof AuthAppFuellungenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_auth/app/bestellungen/$id': typeof AuthAppBestellungenIdRoute
  '/_auth/app/produkte/$id': typeof AuthAppProdukteIdRoute
  '/_auth/app/produkte/neu': typeof AuthAppProdukteNeuRoute
  '/_auth/app/produkte/': typeof AuthAppProdukteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agb'
    | '/colors'
    | '/datenschutz'
    | '/fuellungen'
    | '/galerie'
    | '/impressum'
    | '/kasse'
    | '/kontakt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/warenkorb'
    | '/app'
    | '/login'
    | '/signup'
    | '/bestellung/$orderNo'
    | '/torten/$slug'
    | '/torten/'
    | '/app/fuellungen'
    | '/api/auth/$'
    | '/app/'
    | '/app/bestellungen/$id'
    | '/app/produkte/$id'
    | '/app/produkte/neu'
    | '/app/produkte/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agb'
    | '/colors'
    | '/datenschutz'
    | '/fuellungen'
    | '/galerie'
    | '/impressum'
    | '/kasse'
    | '/kontakt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/warenkorb'
    | '/login'
    | '/signup'
    | '/bestellung/$orderNo'
    | '/torten/$slug'
    | '/torten'
    | '/app/fuellungen'
    | '/api/auth/$'
    | '/app'
    | '/app/bestellungen/$id'
    | '/app/produkte/$id'
    | '/app/produkte/neu'
    | '/app/produkte'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/agb'
    | '/colors'
    | '/datenschutz'
    | '/fuellungen'
    | '/galerie'
    | '/impressum'
    | '/kasse'
    | '/kontakt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/warenkorb'
    | '/_auth/app'
    | '/_guest/login'
    | '/_guest/signup'
    | '/bestellung/$orderNo'
    | '/torten/$slug'
    | '/torten/'
    | '/_auth/app/fuellungen'
    | '/api/auth/$'
    | '/_auth/app/'
    | '/_auth/app/bestellungen/$id'
    | '/_auth/app/produkte/$id'
    | '/_auth/app/produkte/neu'
    | '/_auth/app/produkte/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  AgbRoute: typeof AgbRoute
  ColorsRoute: typeof ColorsRoute
  DatenschutzRoute: typeof DatenschutzRoute
  FuellungenRoute: typeof FuellungenRoute
  GalerieRoute: typeof GalerieRoute
  ImpressumRoute: typeof ImpressumRoute
  KasseRoute: typeof KasseRoute
  KontaktRoute: typeof KontaktRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WarenkorbRoute: typeof WarenkorbRoute
  BestellungOrderNoRoute: typeof BestellungOrderNoRoute
  TortenSlugRoute: typeof TortenSlugRoute
  TortenIndexRoute: typeof TortenIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warenkorb': {
      id: '/warenkorb'
      path: '/warenkorb'
      fullPath: '/warenkorb'
      preLoaderRoute: typeof WarenkorbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasse': {
      id: '/kasse'
      path: '/kasse'
      fullPath: '/kasse'
      preLoaderRoute: typeof KasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fuellungen': {
      id: '/fuellungen'
      path: '/fuellungen'
      fullPath: '/fuellungen'
      preLoaderRoute: typeof FuellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colors': {
      id: '/colors'
      path: '/colors'
      fullPath: '/colors'
      preLoaderRoute: typeof ColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torten/': {
      id: '/torten/'
      path: '/torten'
      fullPath: '/torten/'
      preLoaderRoute: typeof TortenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torten/$slug': {
      id: '/torten/$slug'
      path: '/torten/$slug'
      fullPath: '/torten/$slug'
      preLoaderRoute: typeof TortenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestellung/$orderNo': {
      id: '/bestellung/$orderNo'
      path: '/bestellung/$orderNo'
      fullPath: '/bestellung/$orderNo'
      preLoaderRoute: typeof BestellungOrderNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/fuellungen': {
      id: '/_auth/app/fuellungen'
      path: '/fuellungen'
      fullPath: '/app/fuellungen'
      preLoaderRoute: typeof AuthAppFuellungenRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/produkte/': {
      id: '/_auth/app/produkte/'
      path: '/produkte'
      fullPath: '/app/produkte/'
      preLoaderRoute: typeof AuthAppProdukteIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/produkte/neu': {
      id: '/_auth/app/produkte/neu'
      path: '/produkte/neu'
      fullPath: '/app/produkte/neu'
      preLoaderRoute: typeof AuthAppProdukteNeuRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/produkte/$id': {
      id: '/_auth/app/produkte/$id'
      path: '/produkte/$id'
      fullPath: '/app/produkte/$id'
      preLoaderRoute: typeof AuthAppProdukteIdRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/bestellungen/$id': {
      id: '/_auth/app/bestellungen/$id'
      path: '/bestellungen/$id'
      fullPath: '/app/bestellungen/$id'
      preLoaderRoute: typeof AuthAppBestellungenIdRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
  }
}

interface AuthAppRouteRouteChildren {
  AuthAppFuellungenRoute: typeof AuthAppFuellungenRoute
  AuthAppIndexRoute: typeof AuthAppIndexRoute
  AuthAppBestellungenIdRoute: typeof AuthAppBestellungenIdRoute
  AuthAppProdukteIdRoute: typeof AuthAppProdukteIdRoute
  AuthAppProdukteNeuRoute: typeof AuthAppProdukteNeuRoute
  AuthAppProdukteIndexRoute: typeof AuthAppProdukteIndexRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppFuellungenRoute: AuthAppFuellungenRoute,
  AuthAppIndexRoute: AuthAppIndexRoute,
  AuthAppBestellungenIdRoute: AuthAppBestellungenIdRoute,
  AuthAppProdukteIdRoute: AuthAppProdukteIdRoute,
  AuthAppProdukteNeuRoute: AuthAppProdukteNeuRoute,
  AuthAppProdukteIndexRoute: AuthAppProdukteIndexRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  AgbRoute: AgbRoute,
  ColorsRoute: ColorsRoute,
  DatenschutzRoute: DatenschutzRoute,
  FuellungenRoute: FuellungenRoute,
  GalerieRoute: GalerieRoute,
  ImpressumRoute: ImpressumRoute,
  KasseRoute: KasseRoute,
  KontaktRoute: KontaktRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WarenkorbRoute: WarenkorbRoute,
  BestellungOrderNoRoute: BestellungOrderNoRoute,
  TortenSlugRoute: TortenSlugRoute,
  TortenIndexRoute: TortenIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
